config/routes.rb
OneBody::Application.routes.draw do

  root to: redirect('/stream')

  resource :account do
    member do
      get  :verify_code
      post :verify_code
      get  :select
      post :select
    end
  end

  resources :people do
    collection do
      get  :schema
      get  :import
      post :import
      post :hashify
      post :batch
      put  :import
    end
    member do
      get  :favs
      get  :testimony
    end
    resources :friends do
      collection do
        post :reorder
      end
    end
    resources :relationships do
      collection do
        post :batch
      end
    end
    resource :account do
      member do
        get  :verify_code
        post :verify_code
        get  :select
        post :select
      end
    end
    resource :photo
    resources :groups, :pictures, :groupies, :services, :albums, :notes, :verses
    resource :privacy, :blog, :calendar
  end

  resources :families do
    collection do
      get  :schema
      post :hashify
      post :batch
      post :select
    end
    member do
      post :reorder
    end
    resource :photo
    resources :relationships
  end

  resources :groups do
    collection do
      get  :batch
      post :batch
    end
    resources :memberships do
      collection do
        get    :birthdays
        post   :batch
        delete :batch
      end
      resource :privacy
    end
    resources :messages do
      collection do
        post :new
      end
    end
    resources :attendance do
      collection do
        post :batch
      end
    end
    resource :photo
    resources :notes, :prayer_requests, :albums, :attachments
    resource :calendar
  end

  resources :memberships do
    collection do
      get  :batch
      post :batch
    end
  end

  resources :service_categories do
    collection do
      get :batch_edit
      get :close_batch_edit
    end
  end

  resources :albums do
    resources :pictures do
      member do
        get :next
        get :prev
      end
      resource :photo
    end
  end

  resources :messages do
    resources :attachments
  end

  resources :tags, only: :show

  resources :pictures, :prayer_signups, :authentications, :feeds, :verses, :shares,
            :comments, :prayer_requests
            :generated_files

  resources :notes, except: :index

  resource  :setup, :stream, :session, :search, :printable_directory, :privacy, :pc_sync

  resources :news, as: :news_items
  match 'news', to: 'news#index'

  resource :style
  match 'style.css'          => 'styles#show', format: 'css', as: :style
  match 'style.:browser.css' => 'styles#show', format: 'css', as: :browser_style

  resources :attachments do
    member do
      get :get
    end
  end

  resources :pages, path: 'pages/admin' do
    resources :attachments
  end

  match 'pages/*path' => 'pages#show_for_public', via: :get, as: :page_for_public

  match '/admin' => 'administration/dashboards#show'

  namespace :administration, path: :admin do
    resources :emails do
      collection do
        put :batch
      end
    end
    resources :settings do
      collection do
        put :batch
        put :reload
      end
    end
    resources :files, constraints: {id: /[a-z0-9_]+(\.[a-z0-9_]+)?/}
    resources :attendance do
      collection do
        get :prev
        get :next
      end
    end
    resources :syncs do
      member do
        post :create_items
      end
    end
    resources :deleted_people do
      collection do
        put :batch
      end
    end
    resources :updates, :admins, :membership_requests, :reports
    resource :theme, :api_key, :logo
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base

  include Authority::Abilities
  self.authorizer_name = 'MembershipAuthorizer'

  belongs_to :group
  belongs_to :person
  belongs_to :site

  validates_uniqueness_of :group_id, scope: [:site_id, :person_id]

  scope_by_site_id

  def family; person.family; end

  before_create :generate_security_code

  def generate_security_code
    begin
      code = rand(999999)
      write_attribute :code, code
    end until code > 0
  end

  def self.sharing_columns
    columns.map { |c| c.name }.select { |c| c =~ /^share_/ }
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

  skip_before_filter :authenticate_user, only: %w(show update)
  before_filter :authenticate_user_with_code_or_session, only: %w(show update)

  def show
    # allow email links to work (since they will be GET requests)
    if params[:email]
      update
    else
      raise ActionController::UnknownAction, t('No_action_to_show')
    end
  end

  def index
    @group = Group.find(params[:group_id])
    @can_edit = @logged_in.can_edit?(@group)
    if @logged_in.can_see?(@group)
      @requests = @group.membership_requests
    else
      render text: t('not_authorized'), layout: true, status: 401
    end
  end

  # join group
  def create
    @group = Group.find(params[:group_id])
    @person = Person.find(params[:id])
    if @logged_in.can_edit?(@group) or not @group.approval_required_to_join?
      @group.memberships.create(person: @person)
    elsif me?
      @group.membership_requests.create(person: @person)
      flash[:warning] = t('groups.request_sent')
    end
    redirect_back
  end

  def update
    @group = Group.find(params[:group_id])
    # email on/off
    if params[:email]
      @person = Person.find(params[:id])
      if @logged_in.can_edit?(@group) or @logged_in.can_edit?(@person)
        @group.set_options_for @person, {get_email: (params[:email] == 'on')}
        flash[:notice] = t('groups.email_settings_changed')
        redirect_back
      else
        render text: t('There_was_an_error'), layout: true, status: 500
      end
    # promote/demote
    elsif @logged_in.can_edit?(@group)
      @membership = @group.memberships.find_or_create_by_person_id(params[:id])
      @membership.update_attribute :admin, !params[:promote].nil?
      flash[:notice] = t('groups.user_settings_saved')
      redirect_back
    else
      render text: t('not_authorized'), layout: true, status: 401
    end
  end

  # leave group
  def destroy
    @group = Group.find(params[:group_id])
    @membership = @group.memberships.find_by_person_id(params[:id])
    if @logged_in.can_edit?(@group) or @membership.try(:person) == @logged_in
      if @membership.person and @group.last_admin?(@membership.person)
        flash[:warning] = t('groups.last_admin_remove', name: @membership.person.name)
      else
        @membership.destroy
      end
    end
    respond_to do |format|
      format.html { redirect_back }
      format.js
    end
  end

  def batch
    if params[:person_id]
      batch_on_person
    else
      batch_on_group
    end
  end

  def batch_on_person
    @person = Person.find(params[:person_id])
    if @logged_in.can_edit?(@person) and @logged_in.admin?(:manage_groups)
      groups = (params[:ids] || []).map { |id| Group.find(id) }
      # add groups
      (groups - @person.groups).each do |group|
        group.memberships.create(person: @person)
      end
      # remove groups
      (@person.groups - groups).each do |group|
        group.memberships.find_by_person_id(@person.id).destroy unless group.last_admin?(@person)
      end
      @person.groups.reload
      respond_to do |format|
        format.js
      end
    else
      render text: t('not_authorized'), layout: true, status: 401
    end
  end

  def batch_on_group
    @group = Group.find(params[:group_id])
    group_people = @group.people
    if @logged_in.can_edit?(@group)
      @can_edit = true
      if params[:ids] and params[:ids].is_a?(Array)
        @added = []
        params[:ids].each do |id|
          if request.post?
            person = Person.find(id)
            unless params[:commit] == 'Ignore' or group_people.include?(person)
              @group.memberships.create(person: person) 
              @added << person
            end
            @group.membership_requests.find_all_by_person_id(id).each { |r| r.destroy }
          elsif request.delete?
            if @membership = @group.memberships.find_by_person_id(id)
              @membership.destroy unless @group.last_admin?(@membership.person)
            end
          end
        end
        respond_to do |format|
          format.js
          format.html { redirect_back }
        end
      else
        render text: t('groups.must_specify_ids_list')
      end
    else
      render text: t('not_authorized'), layout: true, status: 401
    end
  end

  def birthdays
    @group = Group.find(params[:group_id])
    if @logged_in.can_edit?(@group)
      @people = @group.people.where('birthday is not null').order("#{sql_month 'people.birthday'}, #{sql_day 'people.birthday'}, people.last_name, people.first_name")
    else
      render text: t('not_authorized'), layout: true, status: 401
    end
  end

end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_person.erb
<%= content_tag :tr, id: "person#{person.id}" do %>
  <td class="icon">
    <a href="<%= url_for person %>">
      <%= render partial: 'people/thumbnail', locals: {person: person} %>
    </a>
  </td>
  <td class="name">
    <%= link_to person.name, person %>
    <% if @group.admin?(person, :exclude_global_admins) %>
      <span class="discreet"><%= t('admin.admin') %></span>
    <% end %>
  </td>
  <% if @can_edit %>
    <td class="action">
      <%= link_to '', group_membership_path(@group, person.id), remote: true, method: :delete, class: 'delete-icon delete-action', style: 'display:none;' %>
      <% if @group.admin?(person, :exclude_global_admins) %>
        <%= link_to t('groups.demote'), group_membership_path(@group, person.id), method: :put, class: 'promote-action', style: 'display:none;' %>
      <% else %>
        <%= link_to t('groups.promote'), group_membership_path(@group, person.id, promote: true), method: :put, class: 'promote-action', style: 'display:none;' %>
      <% end %>
    </td>
  <% end %>
<% end %>

app/views/memberships/_person_birthday.erb
<%= content_tag :tr, id: "person#{person.id}" do %>
  <td class="icon">
    <a href="<%= url_for person %>">
      <%= render partial: 'people/thumbnail', locals: {person: person} %>
    </a>
  </td>
  <td class="name">
    <%= link_to person.name, person %>
    <% if @group.admin?(person, :exclude_global_admins) %>
      <span class="discreet"><%= t('admin.admin') %></span>
    <% end %>
  </td>
  <td class="birthday">
    <%= person.birthday.strftime('%B %d') %>
  </td>
<% end %>

app/views/memberships/batch.js.erb
<% if params[:person_id] %>
  $('#groups_list').html('<%= escape_javascript render(partial: 'people/group_selection') %>');
  $('#group_list_status').html('Groups saved.');
  $('#group_list_status').effect('highlight', {}, '3000', function(){ $(this).hide() });
<% else %>
  $('#memberships').prepend('<%= escape_javascript render(partial: 'person', collection: @added) %>')
  if(deleting_people) $('#memberships .delete-action').show();
  $('<%= @added.map { |p| "#person#{p.id}" }.join(', ') %>').effect('highlight', {}, 3000);
  $('#add_person_name').val('')[0].focus();
  $('#people-heading').html('<%= escape_javascript t('people.person', count: @group.people.count) %>');
<% end %>

app/views/memberships/birthdays.html.erb
<% content_for :sidebar do %>
  <p><%= link_to t('groups.back_to_group', name: @group.name), @group, class: 'left-icon' %></p>
<% end %>

<table class="members" id="memberships">
  <% @people.each do |person| %>
    <%= render partial: 'person_birthday', locals: {person: person} %>
  <% end %>
</table>

app/views/memberships/destroy.js.erb
$('#person<%= params[:id] %>').hide('slow', function(){$(this).detach()});
$('#people-heading').html('<%= escape_javascript t('people.person', count: @group.people.count) %>');

app/views/memberships/index.html.erb
<% content_for :sidebar do %>
  <p><%= link_to t('groups.back_to_group', name: @group.name), @group, class: 'left-icon' %></p>

  <h2><%= t('groups.people_in_group', name: @group.name) %></h2>

  <% if @logged_in.can_edit?(@group) %>
    <% if @group.approved? %>
      <%= form_tag search_path, remote: true do %>
        <%= hidden_field_tag :select_person, true %>
        <p class="double-margin-top">
          <label for="add_person_name"><%= t('groups.add_somebody') %>:</label>
          <%= text_field_tag 'name', nil, id: 'add_person_name' %>
          <% if @group.parents_of %>
            <strong>Remember, this is a group automatically containing
              parents of people in <%= link_to @group.parents_of_group.name, @group.parents_of_group %>.
              Adding people manually should be done sparingly.
          <% end %>
          <%= submit_tag t('search.search_by_name') %>
        </p>
      <% end %>

      <div id="add_member" style="display:none;">
        <%= form_tag batch_group_memberships_path(@group), remote: true, id: 'add_people_form' do %>
          <div id="results"></div>
          <p><%= submit_tag t('search.add_selected') %></p>
        <% end %>
      </div>

      <p>
        <%= link_to t('admin.manage_admins'), '#', id: 'promote-people-action' %>
      </p>
    <% else %>
      <p class="very-strong">
        <%= t('groups.this_group_is_pending_you_may_not_add_people') %>
      </p>
    <% end %>
  <% end %>
<% end %>

<% if @logged_in.can_edit?(@group) and @requests.any? %>
  <h3><%= t('groups.requests') %></h3>
  <%= form_tag batch_group_memberships_path(@group) do |form| %>
    <table>
      <% @requests.each do |req| %>
        <tr>
          <td><%= check_box_tag 'ids[]', req.person.id, false, class: 'checkbox' %></td>
          <td><%= link_to req.person.name, person_url(id: req.person) %></td>
        </tr>
      <% end %>
    </table>
    <p>
      <%= t('groups.select_one_or_more') %>:<br/>
      <input type="submit" name="commit" value="<%= t('groups.accept') %>" style="font-weight:bold;"><br/>
      <input type="submit" name="commit" value="<%= t('groups.ignore') %>">
    </p>
  <% end %>
<% end %>

<h3 id="people-heading"><%= t('people.person', count: @group.people.count) %></h3>

<% if @logged_in.can_edit?(@group) %>
  <div class="heading-action">
    <%= link_to t('groups.remove_people'), '', class: 'delete-icon discreet', id: 'delete-people-action' %>
  </div>
<% end %>

<table class="members" id="memberships">
  <% @group.memberships.all(include: :person, order: 'people.last_name, people.first_name').each do |membership| %>
    <% if person = membership.person %>
      <%= render partial: 'person', locals: {person: person} %>
    <% end %>
  <% end %>
</table>

<% if @group.people.count == 0 %>
  <p><em><%= t('groups.nobody_yet') %></em></p>
<% end %>

<script type="text/javascript">
  deleting_people = false;
  $('#delete-people-action').toggle(function(){
    deleting_people = true;
    $('.delete-action').show();
    $('#delete-people-action').html('<%= escape_javascript t('groups.done_removing_people') %>');
    return false;
  }, function() {
    deleting_people = false;
    $('.delete-action').hide();
    $('#delete-people-action').html('<%= escape_javascript t('groups.remove_people') %>');
    return false;
  });
  $('#promote-people-action').toggle(function(){
    $('.promote-action').show();
    return false;
  }, function() {
    $('.promote-action').hide();
    return false;
  });
</script>