config/routes.rb
OneBody::Application.routes.draw do

  root to: redirect('/stream')

  resource :account do
    member do
      get  :verify_code
      post :verify_code
      get  :select
      post :select
    end
  end

  resources :people do
    collection do
      get  :schema
      get  :import
      post :import
      post :hashify
      post :batch
      put  :import
    end
    member do
      get  :favs
      get  :testimony
    end
    resources :friends do
      collection do
        post :reorder
      end
    end
    resources :relationships do
      collection do
        post :batch
      end
    end
    resource :account do
      member do
        get  :verify_code
        post :verify_code
        get  :select
        post :select
      end
    end
    resource :photo
    resources :groups, :pictures, :groupies, :services, :albums, :notes, :verses
    resource :privacy, :blog, :calendar
  end

  resources :families do
    collection do
      get  :schema
      post :hashify
      post :batch
      post :select
    end
    member do
      post :reorder
    end
    resource :photo
    resources :relationships
  end

  resources :groups do
    collection do
      get  :batch
      post :batch
    end
    resources :memberships do
      collection do
        get    :birthdays
        post   :batch
        delete :batch
      end
      resource :privacy
    end
    resources :messages do
      collection do
        post :new
      end
    end
    resources :attendance do
      collection do
        post :batch
      end
    end
    resource :photo
    resources :notes, :prayer_requests, :albums, :attachments
    resource :calendar
  end

  resources :memberships do
    collection do
      get  :batch
      post :batch
    end
  end

  resources :service_categories do
    collection do
      get :batch_edit
      get :close_batch_edit
    end
  end

  resources :albums do
    resources :pictures do
      member do
        get :next
        get :prev
      end
      resource :photo
    end
  end

  resources :messages do
    resources :attachments
  end

  resources :tags, only: :show

  resources :pictures, :prayer_signups, :authentications, :feeds, :verses, :shares,
            :comments, :prayer_requests
            :generated_files

  resources :notes, except: :index

  resource  :setup, :stream, :session, :search, :printable_directory, :privacy, :pc_sync

  resources :news, as: :news_items
  match 'news', to: 'news#index'

  resource :style
  match 'style.css'          => 'styles#show', format: 'css', as: :style
  match 'style.:browser.css' => 'styles#show', format: 'css', as: :browser_style

  resources :attachments do
    member do
      get :get
    end
  end

  resources :pages, path: 'pages/admin' do
    resources :attachments
  end

  match 'pages/*path' => 'pages#show_for_public', via: :get, as: :page_for_public

  match '/admin' => 'administration/dashboards#show'

  namespace :administration, path: :admin do
    resources :emails do
      collection do
        put :batch
      end
    end
    resources :settings do
      collection do
        put :batch
        put :reload
      end
    end
    resources :files, constraints: {id: /[a-z0-9_]+(\.[a-z0-9_]+)?/}
    resources :attendance do
      collection do
        get :prev
        get :next
      end
    end
    resources :syncs do
      member do
        post :create_items
      end
    end
    resources :deleted_people do
      collection do
        put :batch
      end
    end
    resources :updates, :admins, :membership_requests, :reports
    resource :theme, :api_key, :logo
  end
end

app/models/note.rb
class Note < ActiveRecord::Base

  include Authority::Abilities
  self.authorizer_name = 'NoteAuthorizer'

  belongs_to :person
  belongs_to :group
  has_many :comments, dependent: :destroy
  belongs_to :site

  scope_by_site_id

  validates_presence_of :body

  def name; title; end

  def title=(t)
    write_attribute(:title, t.to_s.any? ? t : nil)
  end

  after_create :create_as_stream_item

  def create_as_stream_item
    return unless person
    StreamItem.create!(
      title:           title,
      body:            body,
      context:         original_url.to_s.any? ? {'original_url' => original_url} : {},
      person_id:       person_id,
      group_id:        group_id,
      streamable_type: 'Note',
      streamable_id:   id,
      created_at:      created_at,
      shared:          group_id || person.share_activity? ? true : false
    )
  end

  after_update :update_stream_items

  def update_stream_items
    StreamItem.find_all_by_streamable_type_and_streamable_id('Note', id).each do |stream_item|
      stream_item.title = title
      stream_item.body  = body
      stream_item.save
    end
  end

  after_destroy :delete_stream_items

  def delete_stream_items
    StreamItem.destroy_all(streamable_type: 'Note', streamable_id: id)
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  load_and_authorize_parent :group, :person, shallow: true
  load_and_authorize_resource

  def index
    @notes = notes.order('created_at desc').page(params[:page])
  end

  def show
    @person = @note.person
  end

  def new
    @note = notes.new
  end

  def create
    @note = notes.new(note_params)
    @note.person = @logged_in
    # FIXME
    #if @note.group
      #raise 'error' unless @note.group.blog? and @note.group.can_post?(@logged_in)
    #end
    if @note.save
      flash[:notice] = t('notes.saved')
      redirect_to @note
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @note.update_attributes(note_params)
      redirect_to @note
    else
      render action: 'edit'
    end
  end

  def destroy
    @note.destroy
    redirect_to [@note.group || @note.person, :notes]
  end

  private

  def note_params
    params.require(:note).permit(:title, :body)
  end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_add_note.erb
<p id="add_note_link" style="display:none;"><%= link_to_function t('notes.add_a_note'), "$('#add_note').show();$('#add_note_link').hide();$('#note_title')[0].focus();", class: 'add-icon' %></p>
<div id="add_note">
  <%= form_tag(new_note_url, method: 'post') %>
    <% if @group %>
      <%= hidden_field_tag 'note[group_id]', @group.id %>
    <% end %>
    <p>
      <label for="note_title"><%= t('notes.title') %>:</label>
      <%= text_field_tag 'note[title]', '', id: 'note_title' %><br/>
      <label for="note_body"><%= t('notes.note') %>:</label><br/>
      <%= text_area_tag 'note[body]', '', id: 'note_body', rows: '10' %><br/>
      <%= submit_tag t('notes.add_note'), style: 'width:100px;' %>
    </p>
  </form>
</div>
<script type="text/javascript">
  $('#add_note').hide();
  $('#add_note_link').show();
</script>

app/views/notes/_form.erb
<%= javascript_include_tag 'tiny_mce/tiny_mce.js' %>
<script type="text/javascript">
  tinyMCE.init({
  	mode: "exact",
  	elements: "note_body",
  	theme: "advanced",
  	convert_newlines_to_brs : true,
  	invalid_elements: "pre,font"
  });
</script>

<%= form_for @note do |form| %>

  <%= error_messages_for(form) %>

  <% if @note.group %>
    <p><em><%= t('notes.this_note_will_be_posted', group: @note.group.name) %></em></p>
    <% if @note.group.private? %>
      <p class="very-strong"><%= t('notes.this_note_will_not_be_private_html') %></p>
    <% end %>
  <% end %>

  <p>
    <%= form.label :title, t('notes.title') %> <%= form.text_field :title %><br/>
    <%= form.label :body, t('notes.body') %>  <%= form.text_field :body, value: sanitize_html(@note.body), rows: 15, cols: 80, style: 'width:100%' %><br/>
    <%= form.submit t('notes.save_note') %>
  </p>
<% end %>

app/views/notes/_meta.erb
<p class="timestamp">
  <% if note.person %><%= t('notes.posted_by') %> <%= link_to note.person.name, note.person %><% end %>
  <% if note.group %><%= t('in') %> <%= link_to note.group.name, note.group %><% end %>
  <%= time_ago_in_words note.created_at %> ago
</p>

app/views/notes/_note.erb
<div class="note">
  <div class="note-heading">
    <div class="note-timestamp">
      <%= t('notes.posted') %> <%= note.created_at.to_s %>
      <% if note.group %>
        <%= t('by') %> <%= link_to(note.person.name, note.person) rescue '?' %>
      <% end %>
    </div>
    <%= link_to note.title, note %>
    <% if @logged_in.can_edit?(note) %>
      <%= link_to '[' + t('edit') + ']', edit_note_path(note), class: 'discreet' %>
      <%= link_to '[' + t('delete') + ']', note_path(note), class: 'discreet', confirm: t('are_you_sure'), method: 'delete' %>
    <% end %>
  </div>

  <div class="note-body"><%= sanitize_html auto_link(note.body) %></div>

  <div class="note-comments">
    <div class="comment-summary">
      <%= render partial: 'comments/comment_summary', locals: {object: note} %>
    </div>
    <p>
      <%= link_to t('comments.add_read_comments'), note, class: 'comment-icon' %>
    </p>
  </div>
</div>
<br/>

app/views/notes/edit.html.erb
<h2><%= t('notes.edit_note') %></h2>

<%= render partial: 'form' %>

app/views/notes/index.html.erb
<h2>
  <%= t('notes.notes') %>
  <% if @person %>
    <%= t('by') %> <%= link_to @person.name, @person %>
  <% elsif @group %>
    <%= t('in') %> <%= link_to @group.name, @group %>
  <% end %>
</h2>

<% @notes.each do |note| %>

  <div class="stream-item">
    <div class="stream-item-meta">
      <% if note.person %>
        <span class="nowrap">
          <a href="<%= url_for note.person %>">
            <%= image_tag note.person.photo.exists? ? note.person.photo.url(:tn) : (note.person.gender == 'Female' ? 'clean/womanoutline.tn.png' : 'clean/manoutline.tn.png'),
              alt: note.person.name %>
          </a>
        </span>
      <% else %>
        <%= image_tag 'clean/manoutline.tn.png', alt: '' %>
      <% end %>
      <div style="clear:left;"></div>
    </div>
    <div class="stream-item-body">
      <% if note.title.to_s.any? %>
        <h2><%= link_to note.title, note %></h2>
        <%= render partial: 'meta', locals: {note: note} %>
        <div>
          <%= sanitize_html auto_link(note.body) %>
        </div>
      <% else %>
        <h2></h2>
        <%= sanitize_html auto_link(note.body) %>
        <%= render partial: 'meta', locals: {note: note} %>
      <% end %>

      <% if note.original_url %>
        <p class="small"><%= t('notes.note_imported_from') %> <%= link_to domain_name_from_url(note.original_url), note.original_url %>.</p>
      <% end %>

      <% if (count = note.comments.count) > 0 %><p><%= pluralize count, t('comment') %></p><% end %>
    </div>
</div>

<% end %>

<%= will_paginate @notes %>

app/views/notes/new.html.erb
<h2><%= t('notes.new_note') %></h2>

<% if @note.group %>
  <p><strong><%= t('notes.creating_note_doesnt_send_email_html') %></strong></p>
<% end %>

<%= render partial: 'form' %>

app/views/notes/show.html.erb
<% content_for :sidebar do %>
  <%= render partial: 'people/photo' %>
  <p>
    <%= t('notes.posted') %> <%= @note.created_at.to_time.to_s %>
    <% if @note.group %><%= t('to') %> <%= link_to @note.group.name, group_url(id: @note.group) %><% end %>
    <%= t('notes.by') %> <%= link_to @note.person.name, person_url(id: @note.person) %>
  </p>
  <% if @logged_in.can_edit?(@note) %>
    <%= link_to t('notes.edit_note'), edit_note_path(@note), class: 'edit-icon' %><br/>
    <%= link_to t('notes.delete_note'), @note, class: 'delete-icon', method: :delete, confirm: t('are_you_sure') %>
  <% end %>
<% end %>

<h1><%= @note.title %></h1>

<div <% if @note.title.to_s.empty? and @note.body.length <= 200 %>class="note-content-big"<% end %>>
  <%= sanitize_html auto_link(@note.body) %>
</div>

<% if @note.original_url %>
  <p class="small"><%= t('notes.note_imported_from') %> <%= link_to domain_name_from_url(@note.original_url), @note.original_url %>.</p>
<% end %>

<h2><%= t('Comments') %></h2>
<%= render partial: 'comments/comments', locals: {object: @note, intro: t('notes.about_this_note') + '.'} %>