config/routes.rb
OneBody::Application.routes.draw do

  root to: redirect('/stream')

  resource :account do
    member do
      get  :verify_code
      post :verify_code
      get  :select
      post :select
    end
  end

  resources :people do
    collection do
      get  :schema
      get  :import
      post :import
      post :hashify
      post :batch
      put  :import
    end
    member do
      get  :favs
      get  :testimony
    end
    resources :friends do
      collection do
        post :reorder
      end
    end
    resources :relationships do
      collection do
        post :batch
      end
    end
    resource :account do
      member do
        get  :verify_code
        post :verify_code
        get  :select
        post :select
      end
    end
    resource :photo
    resources :groups, :pictures, :groupies, :services, :albums, :notes, :verses
    resource :privacy, :blog, :calendar
  end

  resources :families do
    collection do
      get  :schema
      post :hashify
      post :batch
      post :select
    end
    member do
      post :reorder
    end
    resource :photo
    resources :relationships
  end

  resources :groups do
    collection do
      get  :batch
      post :batch
    end
    resources :memberships do
      collection do
        get    :birthdays
        post   :batch
        delete :batch
      end
      resource :privacy
    end
    resources :messages do
      collection do
        post :new
      end
    end
    resources :attendance do
      collection do
        post :batch
      end
    end
    resource :photo
    resources :notes, :prayer_requests, :albums, :attachments
    resource :calendar
  end

  resources :memberships do
    collection do
      get  :batch
      post :batch
    end
  end

  resources :service_categories do
    collection do
      get :batch_edit
      get :close_batch_edit
    end
  end

  resources :albums do
    resources :pictures do
      member do
        get :next
        get :prev
      end
      resource :photo
    end
  end

  resources :messages do
    resources :attachments
  end

  resources :tags, only: :show

  resources :pictures, :prayer_signups, :authentications, :feeds, :verses, :shares,
            :comments, :prayer_requests
            :generated_files

  resources :notes, except: :index

  resource  :setup, :stream, :session, :search, :printable_directory, :privacy, :pc_sync

  resources :news, as: :news_items
  match 'news', to: 'news#index'

  resource :style
  match 'style.css'          => 'styles#show', format: 'css', as: :style
  match 'style.:browser.css' => 'styles#show', format: 'css', as: :browser_style

  resources :attachments do
    member do
      get :get
    end
  end

  resources :pages, path: 'pages/admin' do
    resources :attachments
  end

  match 'pages/*path' => 'pages#show_for_public', via: :get, as: :page_for_public

  match '/admin' => 'administration/dashboards#show'

  namespace :administration, path: :admin do
    resources :emails do
      collection do
        put :batch
      end
    end
    resources :settings do
      collection do
        put :batch
        put :reload
      end
    end
    resources :files, constraints: {id: /[a-z0-9_]+(\.[a-z0-9_]+)?/}
    resources :attendance do
      collection do
        get :prev
        get :next
      end
    end
    resources :syncs do
      member do
        post :create_items
      end
    end
    resources :deleted_people do
      collection do
        put :batch
      end
    end
    resources :updates, :admins, :membership_requests, :reports
    resource :theme, :api_key, :logo
  end
end

app/models/person/friend.rb
class Person
  module Friend
    def request_friendship_with(person)
      if person.friendship_waiting_on?(self)
        # already requested by other person
        self.friendships.create! friend: person
        self.friendship_requests.find_by_from_id(person.id).destroy
        I18n.t('friends.added_as_friend', name: person.name)
      elsif self.can_request_friendship_with?(person)
        # clean up past rejections
        FriendshipRequest.delete_all ['person_id = ? and from_id = ? and rejected = ?', self.id, person.id, true]
        person.friendship_requests.create!(from: self)
        I18n.t('friends.request_sent', name: person.name)
      elsif self.friendship_waiting_on?(person)
        I18n.t('friends.already_pending', name: person.name)
      elsif self.friendship_rejected_by?(person)
        I18n.t('friends.cannot_request', name: person.name)
      else
        raise I18n.t('friends.unknown_state')
      end
    end

    def can_request_friendship_with?(person)
      Setting.get(:features, :friends) and person != self and person.family_id != self.family_id and !friend?(person) and full_access? and person.full_access? and person.valid_email? and person.friends_enabled and !friendship_rejected_by?(person) and !friendship_waiting_on?(person)
    end

    def friendship_rejected_by?(person)
      person.friendship_requests.where(from_id: id, rejected: true).count > 0
    end

    def friendship_waiting_on?(person)
      person.friendship_requests.where(from_id: id, rejected: false).count > 0
    end

    def friend?(person)
      friends.where('friendships.friend_id' => person.id).count > 0
    end
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  before_filter :person_must_be_user, except: %w(index)

  def index
    @person = Person.find(params[:person_id])
    if @logged_in.can_see?(@person)
      @pending = me? ? @person.pending_friendship_requests : []
      @friendships = @person.friendships.all.select { |f| f.friend and @logged_in.can_see?(f.friend) }
    else
      render text: t('people.not_found'), layout: true, status: 404
    end
  end

  # friend_id = Person (other person)
  def create
    @person = Person.find(params[:person_id])
    @other_person = Person.find(params[:friend_id])
    @message = @person.request_friendship_with(@other_person)
    respond_to do |wants|
      wants.html
      wants.js
    end
  end

  # id = FriendshipRequest
  def update
    @person = Person.find(params[:person_id])
    @friendship_request = @person.friendship_requests.find(params[:id])
    if params[:accept]
      @friendship_request.accept
      flash[:notice] = t('people.friendship_accepted')
      redirect_to person_friends_path(@person)
    elsif params[:reject]
      @friendship_request.reject
      flash[:notice] = t('people.friendship_rejected')
      redirect_to person_friends_path(@person)
    else
      render text: t('people.friendship_must_specify'), layout: true, status: 500
    end
  end

  # id = Person (friend)
  def destroy
    @person = Person.find(params[:person_id])
    if @friendship = @person.friendships.find_by_friend_id(params[:id])
      @friendship.destroy
      redirect_to person_friends_path(@person)
    else
      render text: t('people.friend_not_found'), layout: true, status: 404
    end
  end

  def reorder
    @person = Person.find(params[:person_id])
    params[:friends].each_with_index do |id, index|
      if f = @person.friendships.find_by_id(id)
        f.update_attribute :ordering, index
      end
    end
    render nothing: true
  end

  private

    def person_must_be_user
      unless @logged_in.id == params[:person_id].to_i
        render text: t('people.friendship_manage'), layout: true, status: 401
        return false
      end
    end

end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/create.html.erb
<%= @message %>

app/views/friends/create.js.erb
$('#add_friend_<%= @other_person.id %>').hide();
alert('<%= escape_javascript @message %>');

app/views/friends/index.html.erb
<% content_for :sidebar do %>
  <%= render partial: 'people/photo' %>
  <h2><%= t('friends.personal_friends', name: @person.name_possessive) %></h2>
<% end %>

<% if @pending.any? %>
  <div>
    <h3><%= t('friends.pending_requests') %></h3>
    <p><%= t('friends.people_requested') %></p>
    <table class="spaced">
      <% @pending.each do |friendship_request| %>
        <tr>
          <td>
            <a href="<%= url_for person_url(id: friendship_request.from) %>">
              <%= render partial: 'people/thumbnail', locals: {person: friendship_request.from} %>
            </a>
          </td>
          <td>
            <%= link_to friendship_request.from.name, friendship_request.from %>
          </td>
          <td>
            <%= link_to t('friends.accept'), person_friend_path(@logged_in, friendship_request, accept: true), method: 'put', class: 'add-icon' %><br/>
          </td>
          <td>
            <%= link_to t('friends.decline'), person_friend_path(@logged_in, friendship_request, reject: true), method: 'put', confirm: t('are_you_sure'), class: 'delete-icon' %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

<h3><%= t('friends.friends') %></h3>

<% if @friendships.any? %>
  <ul id="friends" style="list-style-type:none;">
    <% @friendships.each do |friendship| %>
      <li id="friendship_<%= friendship.id %>">
        <a href="<%= url_for person_url(id: friendship.friend) %>">
          <%= render partial: 'people/thumbnail', locals: {person: friendship.friend} %>
        </a>
        <%= link_to friendship.friend.name, friendship.friend %>
        (added <%= friendship.created_at.to_time.to_s %>)
        <% if me? %>
          <%= link_to t('friends.remove_from_friends'), person_friend_path(@person, friendship.friend), class: 'delete-icon', method: 'delete', confirm: t('are_you_sure') %>
        <% end %>
      </li>
    <% end %>
  </ul>
  
  <%= javascript_include_tag 'dragdrop.js' %>
<% else %>
  <p><%= t('groups.nobody_yet') %></p>
<% end %>

<% if me? %>
  <p class="double-margin-top">
    <%= link_to t('friends.search_in_the_directory'), new_search_path(search_friends: true), class: 'add-icon' %></p>
  </p>
<% end %>