config/routes.rb
OneBody::Application.routes.draw do

  root to: redirect('/stream')

  resource :account do
    member do
      get  :verify_code
      post :verify_code
      get  :select
      post :select
    end
  end

  resources :people do
    collection do
      get  :schema
      get  :import
      post :import
      post :hashify
      post :batch
      put  :import
    end
    member do
      get  :favs
      get  :testimony
    end
    resources :friends do
      collection do
        post :reorder
      end
    end
    resources :relationships do
      collection do
        post :batch
      end
    end
    resource :account do
      member do
        get  :verify_code
        post :verify_code
        get  :select
        post :select
      end
    end
    resource :photo
    resources :groups, :pictures, :groupies, :services, :albums, :notes, :verses
    resource :privacy, :blog, :calendar
  end

  resources :families do
    collection do
      get  :schema
      post :hashify
      post :batch
      post :select
    end
    member do
      post :reorder
    end
    resource :photo
    resources :relationships
  end

  resources :groups do
    collection do
      get  :batch
      post :batch
    end
    resources :memberships do
      collection do
        get    :birthdays
        post   :batch
        delete :batch
      end
      resource :privacy
    end
    resources :messages do
      collection do
        post :new
      end
    end
    resources :attendance do
      collection do
        post :batch
      end
    end
    resource :photo
    resources :notes, :prayer_requests, :albums, :attachments
    resource :calendar
  end

  resources :memberships do
    collection do
      get  :batch
      post :batch
    end
  end

  resources :service_categories do
    collection do
      get :batch_edit
      get :close_batch_edit
    end
  end

  resources :albums do
    resources :pictures do
      member do
        get :next
        get :prev
      end
      resource :photo
    end
  end

  resources :messages do
    resources :attachments
  end

  resources :tags, only: :show

  resources :pictures, :prayer_signups, :authentications, :feeds, :verses, :shares,
            :comments, :prayer_requests
            :generated_files

  resources :notes, except: :index

  resource  :setup, :stream, :session, :search, :printable_directory, :privacy, :pc_sync

  resources :news, as: :news_items
  match 'news', to: 'news#index'

  resource :style
  match 'style.css'          => 'styles#show', format: 'css', as: :style
  match 'style.:browser.css' => 'styles#show', format: 'css', as: :browser_style

  resources :attachments do
    member do
      get :get
    end
  end

  resources :pages, path: 'pages/admin' do
    resources :attachments
  end

  match 'pages/*path' => 'pages#show_for_public', via: :get, as: :page_for_public

  match '/admin' => 'administration/dashboards#show'

  namespace :administration, path: :admin do
    resources :emails do
      collection do
        put :batch
      end
    end
    resources :settings do
      collection do
        put :batch
        put :reload
      end
    end
    resources :files, constraints: {id: /[a-z0-9_]+(\.[a-z0-9_]+)?/}
    resources :attendance do
      collection do
        get :prev
        get :next
      end
    end
    resources :syncs do
      member do
        post :create_items
      end
    end
    resources :deleted_people do
      collection do
        put :batch
      end
    end
    resources :updates, :admins, :membership_requests, :reports
    resource :theme, :api_key, :logo
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

  belongs_to :person
  belongs_to :related, foreign_key: 'related_id', class_name: 'Person'

  scope_by_site_id

  validates_presence_of :name
  validates_presence_of :other_name, if: Proc.new { |r| r.name == 'other' }
  validates_presence_of :person_id
  validates_presence_of :related_id
  validates_uniqueness_of :name, scope: [:site_id, :other_name, :person_id, :related_id]
  validates_uniqueness_of :other_name, scope: [:site_id, :name, :person_id, :related_id]
  validates_each :name do |record, attribute, value|
    unless I18n.t('relationships.names').keys.map { |r| r.to_s }.include?(value)
      record.errors.add attribute, :inclusion
    end
  end

  def name_or_other
    name == 'other' ? other_name : I18n.t(name, scope: 'relationships.names')
  end

  def reciprocate
    if can_auto_reciprocate?
      Relationship.create(person: related, related: person, name: reciprocal_name)
    end
  end

  def reciprocal_name
    RECIPROCAL_RELATIONSHIP_NAMES[name][person.gender]
  end

  def can_auto_reciprocate?
    !reciprocal_name.nil?
  end

  def self.other_names
    connection.select_values("select distinct other_name from relationships where other_name is not null and other_name != '' and site_id=#{Site.current.id} order by other_name")
  end

  after_save :update_relationships_hash
  after_destroy :update_relationships_hash
  def update_relationships_hash
    person.update_relationships_hash!
  end

  RECIPROCAL_RELATIONSHIP_NAMES = {
    'aunt'            => {'Male' => 'nephew',         'Female' => 'niece'          },
    'brother'         => {'Male' => 'brother',        'Female' => 'sister'         },
    'brother_in_law'  => {'Male' => 'brother_in_law', 'Female' => 'sister_in_law'  },
    'cousin'          => {'Male' => 'cousin',         'Female' => 'cousin'         },
    'daughter'        => {'Male' => 'father',         'Female' => 'mother'         },
    'daughter_in_law' => {'Male' => 'father_in_law',  'Female' => 'mother_in_law'  },
    'father'          => {'Male' => 'son',            'Female' => 'daughter'       },
    'father_in_law'   => {'Male' => 'son_in_law',     'Female' => 'daughter_in_law'},
    'granddaughter'   => {'Male' => 'grandfather',    'Female' => 'grandmother'    },
    'grandfather'     => {'Male' => 'grandson',       'Female' => 'granddaughter'  },
    'grandmother'     => {'Male' => 'grandson',       'Female' => 'granddaughter'  },
    'grandson'        => {'Male' => 'grandfather',    'Female' => 'grandmother'    },
    'husband'         => {                            'Female' => 'wife'           },
    'mother'          => {'Male' => 'son',            'Female' => 'daughter'       },
    'mother_in_law'   => {'Male' => 'son_in_law',     'Female' => 'daughter_in_law'},
    'nephew'          => {'Male' => 'uncle',          'Female' => 'aunt'           },
    'niece'           => {'Male' => 'uncle',          'Female' => 'aunt'           },
    'other'           => {                                                         },
    'sister'          => {'Male' => 'brother',        'Female' => 'sister'         },
    'sister_in_law'   => {'Male' => 'brother_in_law', 'Female' => 'sister_in_law'  },
    'son'             => {'Male' => 'father',         'Female' => 'mother'         },
    'son_in_law'      => {'Male' => 'father_in_law',  'Female' => 'mother_in_law'  },
    'stepbrother'     => {'Male' => 'stepbrother',    'Female' => 'stepsister'     },
    'stepdaughter'    => {'Male' => 'stepfather',     'Female' => 'stepmother'     },
    'stepfather'      => {'Male' => 'stepson',        'Female' => 'stepdaughter'   },
    'stepmother'      => {'Male' => 'stepson',        'Female' => 'stepdaughter'   },
    'stepsister'      => {'Male' => 'stepbrother',    'Female' => 'stepsister'     },
    'stepson'         => {'Male' => 'stepfather',     'Female' => 'stepmother'     },
    'uncle'           => {'Male' => 'nephew',         'Female' => 'niece'          },
    'wife'            => {'Male' => 'husband'                                      }
  }
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_filter :only_admins

  def index
    if params[:person_id]
      person_index
    elsif params[:family_id]
      family_index
    else
      render text: t('relationships.no_person_selected'), layout: true
    end
  end

  def person_index
    @person = Person.undeleted.find(params[:person_id])
    @relationships = @person.relationships.all(include: :related, order: 'people.last_name, people.first_name')
    @inward_relationships = @person.inward_relationships.all(include: :person, order: 'people.last_name, people.first_name')
    @other_names = Relationship.other_names
    @relationship = Relationship.new(person: @person)
    respond_to do |format|
      format.html { render action: 'person_index' }
      format.xml  { render xml: @relationships }
    end
  end

  def family_index
    @family = Family.undeleted.find(params[:family_id])
    people_ids = @family.people.map { |p| p.id }
    @relationships = Relationship.where("person_id in (?) and related_id in (?)", people_ids, people_ids)
    @unique_relationships = {}
    @relationships.each do |relationship|
      @unique_relationships[relationship.related] ||= []
      @unique_relationships[relationship.related] << relationship.name_or_other
      @unique_relationships[relationship.related].uniq!
    end
    @suggested_relationships = @family.suggested_relationships
    render action: 'family_index'
  end

  def create
    if params[:person_id]
      create_for_person
    elsif params[:family_id]
      create_for_family
    else
      render text: t('relationships.no_person_selected'), layout: true
    end
  end

  def create_for_person
    @person = Person.undeleted.find(params[:person_id])
    @related = Person.undeleted.find(Array(params[:ids]).first)
    @relationship = Relationship.new(person: @person, related: @related, name: params[:name], other_name: params[:other_name])
    respond_to do |format|
      if @relationship.save
        format.html { redirect_to person_relationships_path(@person) }
        format.xml  { render xml: @relationship, status: :created, location: person_relationship_path(@person, @relationship) }
      else
        format.html { add_errors_to_flash(@relationship); redirect_to person_relationships_path(@person) }
        format.xml  { render xml: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_for_family
    @family = Family.undeleted.find(params[:family_id])
    params[:people].to_a.each do |person_id, relationships|
      relationships.each do |related_id, relationship|
        Relationship.create(
          person:  @family.people.find(person_id),
          related: @family.people.find(related_id),
          name:    relationship
        )
      end
    end
    redirect_to family_relationships_path(@family)
  end

  def destroy
    @person = Person.undeleted.find(params[:person_id])
    @person.relationship.find(params[:id]).destroy
    respond_to do |format|
      format.xml { head :ok }
    end
  end

  def batch
    @person = Person.undeleted.find(params[:person_id])
    params[:ids].to_a.each do |id|
      if relationship = Relationship.where("id = ? and (person_id = ? or related_id = ?)", id, @person.id, @person.id).first
        if params[:delete]
          relationship.destroy
        elsif params[:reciprocate]
          r = relationship.reciprocate
          if r.nil?
            flash[:warning] ||= ''
            flash[:warning] << t('relationships.cannot_be_reciprocated', name: relationship.related.name) + "\n"
          elsif !r.valid?
            add_errors_to_flash(r)
          end
        end
      end
    end
    redirect_to person_relationships_path(@person)
  end

  private

    def only_admins
      unless @logged_in.admin?(:edit_profiles)
        render text: t('only_admins'), layout: true, status: 401
        return false
      end
    end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/family_index.html.erb
<% content_for :subnav do %>
  <li><%= link_to @family.name, @family %></li>
<% end %>

<h2>Family Relationships for <%= @family.name %></h2>

<% if @relationships.any? %>

  <table id="unique_relationships" class="spaced">
    <tr>
      <th><%= t('name') %></th>
      <th><%= t('relationships.relationship') %>
    <th>
    <% @unique_relationships.each do |person, relationship_names| %>
      <tr>
        <td><%= link_to person.name, person_relationships_path(person) %></td>
        <td><%= relationship_names.join(', ') %></td>
      </tr>
    <% end %>
  </table>
  
  <table id="individual_relationships" style="display:none;" class="spaced">
    <tr>
      <th><%= t('From') %></th>
      <th></th>
      <th><%= t('To') %></th>
      <th><%= t('relationships.relationship') %>
    <th>
    <% @relationships.each do |relationship| %>
      <tr>
        <td><%= link_to relationship.person.name, person_relationships_path(relationship.person) %></td>
        <td><div class="right-icon" style="width:10px;height:16px;"></td>
        <td><%= link_to relationship.related.name, person_relationships_path(relationship.related) %></td>
        <td><%= relationship.name_or_other %></td>
      </tr>
    <% end %>
  </table>
  
  <p><%= link_to_function t('relationships.toggle_individual'), "$('#unique_relationships, #individual_relationships').toggle();" %></p>
  
<% else %>

  <p><em><%= t('none') %></em></p>
  
<% end %>

<% if @family.people.count > 0 %>
  <p><%= link_to_function t('relationships.create_family_relationships'), "$('#auto_generate').show();$(this).hide()" %></p>

  <div id="auto_generate" style="display:none;">
    <%= form_tag family_relationships_path(@family) do %>
      <p><%= t('relationships.create_family_relationships_description') %></p>
      <table class="spaced">
        <tr>
          <th><%= t('From') %></th>
          <th></th>
          <th><%= t('To') %></th>
          <th><%= t('relationships.relationship') %>
        <th>
        <% @suggested_relationships.each do |person, relationships| %>
          <% relationships.each do |related, relationship| %>
            <tr>
              <td><%= link_to person.name, person %></td>
              <td><div class="right-icon" style="width:10px;height:16px;"></td>
              <td><%= link_to related.name, related %></td>
              <td><%= select_tag "people[#{person.id}][#{related.id}]", options_for_select([["(#{t('none')})", '']]+t('relationships.names').invert.sort, relationship.to_sym) %></td>
            </tr>
          <% end %>
        <% end %>
      </table>
      <%= submit_tag t('relationships.create_family_relationships') %>
    <% end %>
  </div>
<% end %>

app/views/relationships/person_index.html.erb
<% content_for :sidebar do %>
  <%= form_tag search_path, remote: true %>
    <%= hidden_field_tag :select_person, true %>
    <p>
      <%= t('relationships.add_a_relationship') %><br/>
      <label for="name"><%= t('search.search_by_name') %></label> <%= text_field_tag 'name' %>
      <br/>
      <%= submit_tag t('relationships.add_relationship_button') %>
    </p>
    <p class="double-margin-top">
      <%= link_to t('relationships.family'), family_relationships_path(@person.family), class: 'people-icon' %>
    </p>
  </form>
  
  <div id="add_member" style="display:none;">
    <%= form_tag person_relationships_path(@person) do %>
      <label for="relationship_name"><%= t('relationships.relationship_type') %></label>
      <%= select_tag :name, options_for_select(['']+t('relationships.names').invert.sort),
        id: 'relationship_name',
        onchange: "if(this.value=='other') { $('#other_name').show()[0].focus() } else { $('#other_name').hide() }" %>
      <%= text_field_tag :other_name, nil, style: 'display:none;' %>
      <script type="text/javascript">
        $('#other_name').autocomplete({source: <%= raw @other_names.inspect %>})
      </script>
      <div id="results"></div>
      <p><%= submit_tag t('search.add_selected') %></p>
    <% end %>
  </div>
<% end %>

<h2><%= @person.name %></h2>

<h3><%= t('relationships.outward') %></h3>

<% if @relationships.any? %>
  <%= form_tag batch_person_relationships_path(@person) do %>
    <table class="spaced">
      <tr>
        <th><input type="checkbox" onclick="$('.outward_relationship_checkbox').attr('checked', this.checked)"/></th>
        <th><%= t('name') %></th>
        <th><%= t('relationships.relationship') %>
      <th>
      <% @relationships.each do |relationship| %>
        <tr>
          <td><%= check_box_tag 'ids[]', relationship.id, false, class: 'outward_relationship_checkbox' %></td>
          <td><%= link_to relationship.related.name, person_relationships_path(relationship.related) %></td>
          <td><%= relationship.name_or_other %></td>
        </tr>
      <% end %>
    </table>
    <p>
      <%= submit_tag t('Delete'), name: 'delete', confirm: t('are_you_sure') %>
      <%= submit_tag t('relationships.Reciprocate'), name: 'reciprocate' %>
    </p>
  <% end %>
<% else %>
  <p><em><%= t('none') %></em></p>
<% end %>

<h3><%= t('relationships.inward') %></h3>

<% if @inward_relationships.any? %>
  <%= form_tag batch_person_relationships_path(@person) do %>
    <table class="spaced">
      <tr>
        <th><input type="checkbox" onclick="$('.inward_relationship_checkbox').attr('checked', this.checked)"/></th>
        <th><%= t('From') %></th>
        <th></th>
        <th><%= t('To') %></th>
        <th><%= t('relationships.relationship') %>
      <th>
      <% @inward_relationships.each do |relationship| %>
        <tr>
          <td><%= check_box_tag 'ids[]', relationship.id, false, class: 'inward_relationship_checkbox' %></td>
          <td><%= link_to relationship.person.name, person_relationships_path(relationship.person) %></td>
          <td><div class="right-icon" style="width:10px;height:16px;"></td>
          <td><%= @person.name %></td>
          <td><%= relationship.name_or_other %></td>
        </tr>
      <% end %>
    </table>
    <p>
      <%= submit_tag t('Delete'), name: 'delete', confirm: t('are_you_sure') %>
      <%= submit_tag t('relationships.Reciprocate'), name: 'reciprocate' %>
    </p>
  <% end %>
<% else %>
  <p><em><%= t('none') %></em></p>
<% end %>